# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: "0.2.0"
  ########################################
  ### ASSERTIONS: System Requirements
  ########################################
  assertions:
    ### Assertion: OS Version
    ### -------------------------------------
    - resource: Microsoft.Windows.Developer/OsVersion
      id: OsVersion
      directives:
        description: Minimum OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: "10.0.22000"

  ########################################
  ### RESOURCES: System Configuration
  ########################################
  resources:
    ### Enable: Show File Extensions and Hidden Files
    ### -------------------------------------
    - resource: Microsoft.Windows.Developer/WindowsExplorer
      id: hiddenfilesshow
      directives:
        description: Show File Extensions and hidden files
        allowPrerelease: true
      settings:
        FileExtensions: Show
        HiddenFiles: Show
    ### Set theme to Dark
    ### -------------------------------------
    - resource: Microsoft.Windows.Developer/EnableDarkMode
      id: darkmode
      directives:
        description: Set theme to Dark
        allowPrerelease: true
      settings:
        Ensure: Present
        RestartExplorer: true
    ### Install Visual Studio Code using winget
    ### -------------------------------------
    ### Install CLIs, SDKs & Tools
    ########################################
    ### Install Powershell
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: powershell
      directives:
        description: Install Powershell
        allowPrerelease: true
      settings:
        id: Microsoft.PowerShell
    ### Install Visual Studio Code
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vscode
      directives:
        description: Install Microsoft Visual Studio Code
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        ensure: Present
    ### Install Git
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: git
      directives:
        description: Install Git
        allowPrerelease: true
      settings:
        id: Git.Git
        ensure: Present
    ### Install Oh My Posh
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: ohmyposh
      directives:
        description: Install Oh My Posh
        allowPrerelease: true
      settings:
        id: JanDeDobbeleer.OhMyPosh
        ensure: Present
